### ISSUE TITLE
please make deploy to heroku button

### ISSUE THREAD

**Issue by kakamband** [tristanlatr/WPWatcher#44]
hi tristanlatr,
please make deploy to heroku button for don't use my personal system hardware & vps req.
its so important for me 
waiting for your response
finest regards

**Comment by tristanlatr** [comment]
Hello @kakamband ,

Sorry I don't understand your request.
What's the matter with heroku?

**Comment by tristanlatr** [comment]
Hi @kakamband ,

I've been looking at how to "make deploy to heroku button"... Here: https://devcenter.heroku.com/articles/heroku-button#creating-the-app-json-file

And I'm still unsure if this is even applicable to WPWatcher. It's supposed to be for web application, WPWatcher is not a web application, it only works with CLI.

Please can you elaborate about the use case of such a "button" ?

Thanks

**Comment by kakamband** [comment]
hi @tristanlatr
i means can you make it deployable to heroku or netlify or repl.it or vercel (zeit .now) for free cloud dyno gear to monitor all the time my outsite wordpress ?
waiting for your response
finest regards

**Comment by tristanlatr** [comment]
What does that mean "Make it deployable"?
What is it that need to be changed/added to implement such a functionality ?

**Comment by tristanlatr** [comment]
@kakamband Any idea ?

**Comment by tristanlatr** [comment]
I will close this issue since we don't have any clue where to start to make it "deployable"... It's really only a CLI app.
