### ISSUE TITLE
Not running scans when configured as cron job

### ISSUE THREAD

**Issue by mattias-pa-vistrom** [tristanlatr/WPWatcher#49]
Hello,

I have a problem where WPWatcher refuses to do all of the work when configured as a cron job. I set it to run with verbose mode and to output logging to a file in my home folder, and all I can se it doing is sort of faking a run, almost as if it was dry-running.

`0 * * * * /home/user/.local/bin/wpwatcher -v --conf /home/user/wpwatcher.conf >> /home/user/wpwatcher.log`

Approximate config:
```
DEBUG - WPWatcher configuration:
wp_sites                        =       [{"url": "..."}, {"url": "..."}, {"url": "..."}, {"url": "..."}]
send_email_report               =       True
send_errors                     =       True
email_to                        =       ["user@domain.com"]
send_infos                      =       True
quiet                           =       True
verbose                         =       True
attach_wpscan_output            =       True
fail_fast                       =       False
api_limit_wait                  =       False
daemon                          =       False
daemon_loop_sleep               =       0:00:00
resend_emails_after             =       0:00:00
wp_reports                      =       /home/user/.wpwatcher/wp_reports.json
asynch_workers                  =       4
log_file                        =       /home/user/.wpwatcher/wpwatcher.log
follow_redirect                 =       True
wpscan_output_folder            =       /home/user/.wpwatcher/wpscan-results/
wpscan_args                     =       ["--format", "json", "--random-user-agent", "--update"]
scan_timeout                    =       0:25:00
false_positive_strings          =       []
send_warnings                   =       True
email_errors_to                 =       ["user@domain.com"]
wpscan_path                     =       wpscan
smtp_server                     =       smtp.example.com:587
smtp_auth                       =       True
smtp_user                       =       account@example.com
smtp_pass                       =       ***
smtp_ssl                        =       True
from_email                      =       scan@domain.com
use_monospace_font              =       True
syslog_server                   =
syslog_port                     =       514
syslog_stream                   =       SOCK_STREAM
syslog_kwargs                   =       {"enterprise_id": 42, "msg_as_utf8": true, "utc_timestamp": true}
```

It outputs the correct config, it then continues to output:

```
INFO - Starting scans on 22 configured sites
INFO - Scanning site https://www.my-first-site-to-scan.com/
INFO - Scanning site https://www.the-next-site-to-scan.com/
DEBUG - Running WPScan command: wpscan --version --format json --no-banner
.....
```

It all looks like it is running correctly, but looking at HTOP I see that WPWatcher is running from start to stop in less than half a second, and I receive no emails. If I run the exact same command as the same user but not in cron it runs as it should, it takes some time and I receive emails for all scanned sites etc.

I'm running a fresh install of Ubuntu 20.04.1 LTS with Python 3.8.5, ruby 2.7.0p0, WPWatcher 2.4.8 and WPScan 3.8.15.

Any idea what I'm missing here? Is this a bug?

**Comment by tristanlatr** [comment]
Hi @mattias-pa-vistrom , Thanks for the report. 

The DEBUG output is supposed to print "raw" WPScan results, so here it is JSON data, do you see JSON data in the logfile ?

> it then continues to output

No traceback in the log file ` /home/user/.wpwatcher/wpwatcher.log` ? 

> If I run the exact same command as the same user but not in cron it runs as it should

This look like an environnement issue, please configure full PATH to wpscan executable like `/usr/local/rvm/gems/default/wrappers/wpscan` (with RVM)

If it's not a configuration issue, please pull the latest WPWatcher version from github and install it manually to test if the latest version is still buggy.

**Comment by mattias-pa-vistrom** [comment]
Setting the full WPScan path in config did the trick. WPScan was in my $PATH but for some reason it needed the absolute path in wpwatcher.conf to find it. It now seems to work as expected.
