### ISSUE TITLE
Integrate HTML Page Export for Vulnerability Reports

### ISSUE THREAD

**Issue by thatvideoshopguy** [tristanlatr/WPWatcher#60]
### Description

To provide users with an alternative, easily shareable format for vulnerability reports, it would be advantageous to add an HTML page export feature to WPWatcher. This feature would allow users to generate an interactive, visually appealing report that can be viewed in any web browser, shared with team members, or archived for future reference.

**Comment by tristanlatr** [comment]
This is probably the easiest feature to implement, we can currently export the results as text with `wpwatcher --show url`. 
It would be quite obvious to implement `wpwatcher --show-html url`.

**Comment by thatvideoshopguy** [comment]
That sounds like the most logical flag for the end-user. Can I have give it a try in a separate PR? Or do you want to build out the logic and I can assist with the shaping of the page layout after you've made the update?

**Comment by tristanlatr** [comment]
This is literally a micro change, no need to shape the page layout etc, it's all already done in [wpscan_out_parse](https://github.com/tristanlatr/wpscan_out_parse/blob/master/wpscan_out_parse/formatter.py).

We just need to edit the function [show()](https://github.com/tristanlatr/WPWatcher/blob/ae5fdd715fa5efd38a0dbb7b1a932667b8f3e5de/wpwatcher/cli.py#L83) to accept a `format` argument and pass it along to `format_results()` function, and plug everything together when option `--show-html` is provided.
