### ISSUE TITLE
Consider using the WPScanAPI directly to improve performance and simplify dependencies

### ISSUE THREAD

**Issue by thatvideoshopguy** [tristanlatr/WPWatcher#65]
### Description
Currently, WPWatcher relies on the Ruby-based [WPScan](https://github.com/wpscanteam/wpscan) tool to perform WordPress vulnerability scans. This adds a dependency on Ruby and the WPScan tool, which can complicate the installation process and might affect performance.

An alternative approach would be to use the WPScan API directly within the Python application. This could potentially improve performance, simplify dependencies, and allow for more control over the scanning process. However, this change would require a significant refactor of the existing codebase to integrate the WPScan API directly.

### Benefits
- **Improved performance:** By using the API directly, we can potentially reduce overhead and improve the performance of WPWatcher.
- **Simplified dependencies:** Removing the dependency on the Ruby-based WPScan tool could make it easier to install and use WPWatcher.
- **Increased control:** By interacting with the WPScan API directly, we can have more control over the scanning process and possibly offer more features or customisations.

### Potential Drawbacks
- **Significant refactoring:** This change would require a substantial rewrite of the existing codebase to integrate the WPScan API directly.

This issue is to discuss the feasibility of this change and gather input from contributors on whether it would be a valuable improvement to WPWatcher.

**Comment by tristanlatr** [comment]
WPWatcher is a wrapper for `wpscan` and it's supposed to stay that way.

**Comment by thatvideoshopguy** [comment]
Fair enough. I thought that perhaps since the wrapper still requires an API key it may be easier for maintainability to make this purely a python project and avoid the additional overhead of Ruby. But, yes it would be no small feat to refactor the codebase.
